language: node_js
node_js:
  - "8"
cache: 
  yarn: true
  directories:
    - "node_modules"
script:
  - yarn test
  - yarn run docs
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs
  keep-history: true
  on:
    branch: master