language: node_js
node_js:
  - "8"
cache: 
  yarn: true
  directories:
    - "node_modules"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: tests
  keep-history: true
  on:
    branch: master